function combinedMask = getAnyType( rewardType, fieldNames )
% % getAnyType %
%PURPOSE:   Get trial mask defined by an OR operation of unlimited trial conditions
%AUTHORS:   MJ Siniscalchi, 170113
%
%INPUT ARGUMENTS
%   rewardType:     field generated by sucrose_getBoutData()
%   fieldNames:     the field names involved
%
%OUTPUT ARGUMENTS
%   combinedMask:   mask where all fields are satisfied, i.e. an AND operation

temp = [];
for i = 1:length(fieldNames)
    temp = [temp strcmp(rewardType,fieldNames{i})]; %trialMasks as columns of array
end
combinedMask = any(temp,2); %true if any element is non-zero

end

