function plot_days_stats(val,subj_info,params)
% % plot_days_stats %
%PURPOSE:   Plot behavioral performance across days
%AUTHORS:   AC Kwan 170617

%INPUT ARGUMENTS
%   val:          Vector of the values to be plotted across days
%   subj_info:    Structure generated by groupbysuject().
%   params:       Plotting parameters

%%
numType = size(val,2);   %number of lines to plot per panel
if numType == 1
    col={'k'};
elseif numType == 3
    col={[0.33 0 0.33],[0.66 0 0.66],[1 0 1]};
else
    col={[0 0 0],[0.33 0 0.33],[0.66 0 0.66],[1 0 1]};
end

%% organize data based on subjects
valbySubj = nan(max(subj_info.subjectID),max(subj_info.acqdate),numType);
for j=1:size(val,1)
    for k=1:numType
        valbySubj(subj_info.subjectID(j),subj_info.acqdate(j),k)=val(j,k);
    end
end

%% plot as a function of day per subject
figure;

%number of conditions (e.g., control, susceptible, resilient)
if isfield(subj_info,'subjClassif') %split into susceptible/resilient
    subjCond = subj_info.subjClassif;
    subjCondLabel = subj_info.classiflabel;
else
    subjCond = subj_info.subjCond;
    subjCondLabel = subj_info.condlabel;
end
condList = unique(subjCond);
nCond = numel(condList);

dat = [];
for j=1:nCond
    
    %% bar plot of specific days
    subplot(2,3,j); hold on;
    
    h=[]; 
    for kk=1:numType  %for each reinforcement block type, plot a line
        
        %subset of data for the specific condition, and specified days, and block type
        temp=[];
        for ll=1:numel(params.daysForBarPlot)
            temp(:,ll,:) = nanmean(valbySubj(subjCond==condList(j),params.daysForBarPlot{ll},kk),2);   %arrange across the specified days
        end
        nanInRows = sum(isnan(temp),2)>0;  %any subject with missing data
        temp = temp(~nanInRows,:);         %remove subjects with missing data
        
        h(1)=bar(kk-0.25,nanmean(temp(:,1)),0.15,'EdgeColor','k','LineWidth',3,'FaceColor','w');
        h(2)=bar(kk,nanmean(temp(:,2)),0.15,'EdgeColor','r','LineWidth',3,'FaceColor','w');
        h(3)=bar(kk+0.25,nanmean(temp(:,3)),0.15,'EdgeColor','k','LineWidth',3,'FaceColor',[0.9 0.9 0.9]);
        plot([kk-0.25 kk-0.25],nanmean(temp(:,1))+nanstd(temp(:,1))/sqrt(sum(~isnan(temp(:,1))))*[-1 1],'k','LineWidth',3);
        plot([kk kk],nanmean(temp(:,2))+nanstd(temp(:,2))/sqrt(sum(~isnan(temp(:,2))))*[-1 1],'r','LineWidth',3);
        plot([kk+0.25 kk+0.25],nanmean(temp(:,3))+nanstd(temp(:,3))/sqrt(sum(~isnan(temp(:,3))))*[-1 1],'k','LineWidth',3);
        for jj=1:size(temp,1)
            plot([kk-0.25 kk kk+0.25],[temp(jj,1) temp(jj,2) temp(jj,3)],'-','Color',[0.5 0.5 0.5],'LineWidth',1);
        end
        
        dat{j}(:,:,kk) = temp; %saves data to do stats later
    end
    plot([0.5 numType+0.5],params.ybaseline*[1 1],'k--','LineWidth',2);
    
    title([subjCondLabel{j} ' (n = ' int2str(size(temp,1)) ')']);
    xlabel('Block type');
    xlim([0.5 3.5]); ylim(params.yrange1);
    if j==1
        ylabel(params.ytitle);
        if isfield(params,'barlabels')
            legend(h,params.barlabels,'location','northwest');
            legend boxoff;
        end
    end
    set(gca,'xticklabel',params.linelabels,'xtick',1:1:3);
 
end

%% anova test for the bar graph
for j=1:nCond
    
    disp(['----- Condition ' subjCondLabel{j} ' --- ANOVA:']);
    currdat = dat{j};
    
    subj=[]; day=[]; rtype=[];
    for ii=1:size(currdat,1)          %subject
        for jj=1:size(currdat,2)      %days
            for kk=1:size(currdat,3)  %reward type
                subj(ii,jj,kk)=ii;
                day(ii,jj,kk)=jj;
                rtype(ii,jj,kk)=kk;
            end
        end
    end
    
    currdat = currdat(:);
    subj = subj(:);
    day = day(:);
    rtype = rtype(:);
    
    % repeated measures ANOVA
    % https://www.mathworks.com/matlabcentral/newsreader/view_thread/58226
    terms=[1 0 0; 0 1 0; 1 1 0];  %interaction terms

    % nested may be more accurate, but cannot use with post hoc multiple comparison
    %    [p,tab,stats]=anovan(currdat,{rtype day subj},'random',3,'nested',[0 0 0; 0 0 0; 1 0 0],'model',terms,'varnames',{'Reward type' 'Days' 'Subjects'},'display','off');
    [p,tab,stats]=anovan(currdat,{rtype day subj},'random',3,'model',terms,'varnames',{'Reward type' 'Days' 'Subjects'},'display','off');
    tab
    [c,m,h,nms] = multcompare(stats,'Dimension',[2],'display','off');
    c
    
end

end


