function output = sucrose_blocks(blocks,sepType)
% % sucrose_blocks %
%PURPOSE:   Plot number of rewards by block
%AUTHORS:   AC Kwan 170609
%
%INPUT ARGUMENTS
%   sessionData:  Structure generated by sucrose_getSessionData().
%   blocks:       Structure generated by sucrose_getBlockData().
%
%OUTPUT ARGUMENTS
%   output:       Analysis output, to be sent to plot_sucrose_blocks().
%

%% Reward per block; pad the rest with zero
maxBlock = 100;  %set up variable to accomodate up to more blocks than animals would ever do

output.typeLabel = sepType;
output.nBlock = numel(blocks.reward);

% extrapolate the expected reward type for each block up to maxBlock
output.blocksRewardType = repmat(blocks.rewardType(1:4),maxBlock/4,1);

% block not reached = zero actions completed 
output.blocksReward = [blocks.reward; zeros(maxBlock-output.nBlock,1)];

end


