function output=sucrose_licks(sessionData,boutType,sepType,trigTime,edges)
% % sucrose_licks %
%PURPOSE:   Analyze lick rate for different type
%AUTHORS:   AC Kwan 170609
%
%INPUT ARGUMENTS
%   sessionData:  Structure generated by sucrose_getSessionData().
%   boutType:     Subfield in structure generated by sucrose_getBoutData().
%   sepType:      The text string to separate the type of bouts
%   trigTime:     The event times around which to determine lick rate
%   edges:        The edges used for a histc() operation to get lick rate histogram
%
% To plot the output, use plot_sucrose_licks().

%%
nType = numel(sepType);
for j=1:nType  %for each reward type
    lickTimesListAll{j} = [];  %will determine a list of licks made relative to the trigTime
end

eventCount = zeros(nType,1);  %will also count how many trigTime is associated with each reward type

for j=1:nType  %for each reward type
    if ischar(sepType{j})
        crit = find(strcmp(boutType,sepType{j})); %the relevant reward type
    elseif isa(sepType{j},'double')
        crit = find(boutType == sepType{j});
    else
        error('Error in sucrose_lick: unknown data type');
    end
    
    for k=1:numel(crit)
        
        % lick times relative to that event time
        lickTimesAligned = sessionData.lickTimes - (trigTime(crit(k)));
        lickTimesAligned = lickTimesAligned(lickTimesAligned >= edges(1) & lickTimesAligned <= edges(end));
        
        % collect those licks into one long list
        lickTimesListAll{j} = [lickTimesListAll{j}; lickTimesAligned];
        % collect those licks by trial
        lickTimesListByType{j}.trial{eventCount(j)+1} = lickTimesAligned;
        
        eventCount(j) = eventCount(j) + 1;
        
    end
end

%use the histc function to convert lick times to lick rate, normalized by number of events
lickRateByType = nan(numel(edges),nType);
edgeWidth=nanmean(diff(edges));
for j=1:nType  %for each reward type
    lickRateByType(:,j) = histc(lickTimesListAll{j},edges)/edgeWidth/eventCount(j);
end

output.edges = edges;
output.sepType = sepType;
output.lickRateByType=lickRateByType(1:end-1,:); %histc, the last bin is not used
output.lickTimesByType=lickTimesListByType;

